version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "3001:3001"

  postgres:
    build: ./database/
    environment:
      POSTGRES_PASSWORD: postgres